name: Health Check

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  Health-check-pokemon:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://bitter-wood-9241.fly.dev/health
          max-attempts: 3
          retry-delay: 5s
